// ============================================================
// CineZoneBD – Sample Data
// ============================================================
const SAMPLE_MOVIES = [
  {
    id: "m1",
    title: "Dhurandhar: The Final Chapter (2026)",
    poster: "https://placehold.co/300x420/1a1a2e/e94560?text=Dhurandhar%0AThe+Final",
    type: "movie",
    language: "hindi",
    dubbed: false,
    genre: ["action","thriller"],
    quality: "4K uHDRip",
    views: "231.26K",
    rating: "8.2",
    status: "completed",
    pinned: true,
    featured: true,
    year: 2026,
    description: "In this epic conclusion, a master tactician must outwit an international crime syndicate using wits, grit and an unbeatable team.",
    episodes: null,
    tags: ["WEB-DL","Dual Audio"],
    addedDate: "2026-03-20"
  },
  {
    id: "m2",
    title: "Love Sitter (2026) Full HD",
    poster: "https://placehold.co/300x420/1a1a2e/f5a623?text=Love+Sitter%0A2026",
    type: "movie",
    language: "bangla",
    dubbed: false,
    genre: ["romance","comedy"],
    quality: "WEB-DL",
    views: "29.37K",
    rating: "7.5",
    status: "completed",
    pinned: true,
    featured: false,
    year: 2026,
    description: "A charming romantic comedy about a babysitter who unexpectedly falls in love with a single dad.",
    episodes: null,
    tags: ["WEB-DL","Bangla"],
    addedDate: "2026-03-18"
  },
  {
    id: "m3",
    title: "GOAT (2026) Hindi ORG",
    poster: "https://placehold.co/300x420/1a1a2e/00d4aa?text=GOAT%0A2026",
    type: "movie",
    language: "hindi",
    dubbed: false,
    genre: ["action","drama"],
    quality: "WEB-DL",
    views: "520",
    rating: "7.8",
    status: "completed",
    pinned: true,
    featured: false,
    year: 2026,
    description: "An adrenaline-pumping action drama that follows the greatest of all time as he faces his biggest challenge yet.",
    episodes: null,
    tags: ["WEB-DL","Hindi ORG"],
    addedDate: "2026-03-19"
  },
  {
    id: "m4",
    title: "Ali (2026) Bangla Full HD",
    poster: "https://placehold.co/300x420/1a1a2e/e94560?text=Ali%0A2026",
    type: "movie",
    language: "bangla",
    dubbed: false,
    genre: ["action","drama"],
    quality: "WEB-DL",
    views: "33.91K",
    rating: "8.0",
    status: "completed",
    pinned: true,
    featured: true,
    year: 2026,
    description: "Based on a true story, Ali traces the journey of a young fighter who rises from nothing to become a champion.",
    episodes: null,
    tags: ["WEB-DL","Bangla"],
    addedDate: "2026-03-17"
  },
  {
    id: "m5",
    title: "Border 2 (2026) Full HD",
    poster: "https://placehold.co/300x420/1a1a2e/f5a623?text=Border+2%0A2026",
    type: "movie",
    language: "hindi",
    dubbed: false,
    genre: ["action","war"],
    quality: "4K uHDRip",
    views: "152.71K",
    rating: "8.5",
    status: "completed",
    pinned: true,
    featured: true,
    year: 2026,
    description: "The legendary war saga continues. Soldiers fight at the border against all odds in this emotionally charged sequel.",
    episodes: null,
    tags: ["4K uHDRip","Hindi"],
    addedDate: "2026-03-15"
  },
  {
    id: "m6",
    title: "Peaky Blinders: The Immortal Man (2026)",
    poster: "https://placehold.co/300x420/1a1a2e/8b5cf6?text=Peaky+Blinders%0AImmortal+Man",
    type: "movie",
    language: "dual",
    dubbed: true,
    genre: ["thriller","drama"],
    quality: "4K uHDRip",
    views: "29.6K",
    rating: "9.1",
    status: "completed",
    pinned: true,
    featured: true,
    year: 2026,
    description: "Tommy Shelby faces his greatest enemy yet in this explosive film that continues the Peaky Blinders legacy.",
    episodes: null,
    tags: ["4K uHDRip","Dual Audio","Hindi ORG"],
    addedDate: "2026-03-14"
  },
  {
    id: "m7",
    title: "Vishnu Vinyasam (2026) Hindi ORG",
    poster: "https://placehold.co/300x420/1a1a2e/00d4aa?text=Vishnu%0AVinyasam",
    type: "movie",
    language: "dual",
    dubbed: true,
    genre: ["action","mythology"],
    quality: "WEB-DL",
    views: "46.47K",
    rating: "7.6",
    status: "completed",
    pinned: true,
    featured: false,
    year: 2026,
    description: "A mythological action spectacle that brings the divine stories of Vishnu to life in a stunning cinematic experience.",
    episodes: null,
    tags: ["WEB-DL","Dual [Hindi-Telugu]"],
    addedDate: "2026-03-12"
  },
  {
    id: "m8",
    title: "Darkroom (2024) Thriller",
    poster: "https://placehold.co/300x420/1a1a2e/e94560?text=Darkroom%0A2024",
    type: "movie",
    language: "dual",
    dubbed: true,
    genre: ["thriller","mystery"],
    quality: "WEB-DL",
    views: "5.81K",
    rating: "3.6",
    status: "completed",
    pinned: false,
    featured: false,
    year: 2024,
    description: "A claustrophobic psychological thriller that unravels layers of deception inside a locked photography studio.",
    episodes: null,
    tags: ["WEB-DL","Dual Audio"],
    addedDate: "2026-03-10"
  },
  {
    id: "m9",
    title: "College Days (2026) Bangla Full HD",
    poster: "https://placehold.co/300x420/1a1a2e/f5a623?text=College+Days%0A2026",
    type: "movie",
    language: "bangla",
    dubbed: false,
    genre: ["romance","comedy"],
    quality: "WEB-DL",
    views: "30.21K",
    rating: "8.1",
    status: "completed",
    pinned: true,
    featured: false,
    year: 2026,
    description: "A heartwarming Bangladeshi film about the unforgettable memories, friendships, and first love of college days.",
    episodes: null,
    tags: ["WEB-DL","Bangla"],
    addedDate: "2026-03-09"
  },
  {
    id: "m10",
    title: "Vijeyta (2025) Full HD",
    poster: "https://placehold.co/300x420/1a1a2e/8b5cf6?text=Vijeyta%0A2025",
    type: "movie",
    language: "hindi",
    dubbed: false,
    genre: ["action","drama"],
    quality: "HDTC",
    views: "42.14K",
    rating: "7.2",
    status: "completed",
    pinned: false,
    featured: false,
    year: 2025,
    description: "A powerful drama that tells the story of a soldier who overcomes all obstacles to emerge as a true victor.",
    episodes: null,
    tags: ["HDTC","Hindi"],
    addedDate: "2026-03-08"
  },
  {
    id: "m11",
    title: "Doa (2026) Bangla Full HD",
    poster: "https://placehold.co/300x420/1a1a2e/e94560?text=Doa%0A2026",
    type: "movie",
    language: "bangla",
    dubbed: false,
    genre: ["drama","romance"],
    quality: "WEB-DL",
    views: "2.08K",
    rating: "7.0",
    status: "completed",
    pinned: false,
    featured: false,
    year: 2026,
    description: "An emotional drama about the power of prayers, family bonds, and sacrificial love in contemporary Bangladesh.",
    episodes: null,
    tags: ["WEB-DL","Bangla"],
    addedDate: "2026-03-07"
  },
  {
    id: "m12",
    title: "Aa Okkati Adakku (2024) Hindi-Telugu",
    poster: "https://placehold.co/300x420/1a1a2e/00d4aa?text=Aa+Okkati%0AAdakku",
    type: "movie",
    language: "dual",
    dubbed: true,
    genre: ["comedy","romance"],
    quality: "WEB-DL",
    views: "4K",
    rating: "5.3",
    status: "completed",
    pinned: false,
    featured: false,
    year: 2024,
    description: "A laugh-out-loud Telugu comedy about a groom's frantic search for a lost wedding document on his wedding day.",
    episodes: null,
    tags: ["WEB-DL","Dual [Hindi-Telugu]","4K"],
    addedDate: "2026-03-06"
  }
];

const SAMPLE_SERIES = [
  {
    id: "s1",
    title: "Bachelor Point (2026) S05 Ep 73-80 Added",
    poster: "https://placehold.co/300x420/16213e/e94560?text=Bachelor+Point%0AS05",
    type: "series",
    language: "bangla",
    dubbed: false,
    genre: ["comedy","drama"],
    quality: "WEB-DL",
    views: "377.69K",
    rating: "9.0",
    status: "ongoing",
    pinned: true,
    featured: true,
    year: 2026,
    description: "The hugely popular Bangladeshi web series returns with its 5th season, bringing more comedy, drama, and unforgettable hostel life moments.",
    episodes: "S05 Ep 73-80",
    tags: ["WEB-DL","Bangla","Series"],
    addedDate: "2026-03-21"
  },
  {
    id: "s2",
    title: "CID (2025) S02 [Ep01-88 Added] Bengali Dubbed",
    poster: "https://placehold.co/300x420/16213e/f5a623?text=CID%0AS02+Dubbed",
    type: "series",
    language: "bangla",
    dubbed: true,
    genre: ["crime","thriller"],
    quality: "WEB-DL",
    views: "1.55M",
    rating: "7.0",
    status: "ongoing",
    pinned: false,
    featured: true,
    year: 2025,
    description: "India's iconic police procedural drama returns in Bengali dubbed for Bangladeshi audiences. The CID team tackles the most baffling cases.",
    episodes: "S02 Ep 1-88",
    tags: ["WEB-DL","Bengali Dubbed","Series"],
    addedDate: "2026-03-20"
  },
  {
    id: "s3",
    title: "Cactus (2026) S01 Epi 1-6 Completed",
    poster: "https://placehold.co/300x420/16213e/00d4aa?text=Cactus%0AS01+Complete",
    type: "series",
    language: "bangla",
    dubbed: false,
    genre: ["drama","thriller"],
    quality: "WEB-DL",
    views: "97.29K",
    rating: "8.3",
    status: "completed",
    pinned: true,
    featured: false,
    year: 2026,
    description: "A gritty Bangladeshi thriller series about survival against social injustice in a harsh urban landscape.",
    episodes: "S01 Ep 1-6 (Complete)",
    tags: ["WEB-DL","Bangla","Complete"],
    addedDate: "2026-03-19"
  },
  {
    id: "s4",
    title: "Naagin (2025) S07 Epi 1-26 Added",
    poster: "https://placehold.co/300x420/16213e/8b5cf6?text=Naagin%0AS07",
    type: "series",
    language: "hindi",
    dubbed: false,
    genre: ["fantasy","drama"],
    quality: "WEB-DL",
    views: "342.43K",
    rating: "3.6",
    status: "ongoing",
    pinned: false,
    featured: false,
    year: 2025,
    description: "The supernatural shapeshifter drama continues its seventh season with new twists, divine powers, and family vendettas.",
    episodes: "S07 Ep 1-26",
    tags: ["WEB-DL","Hindi","Series"],
    addedDate: "2026-03-18"
  },
  {
    id: "s5",
    title: "Laughter Chefs S03 Ep 1-36 Entertainment (2025)",
    poster: "https://placehold.co/300x420/16213e/f5a623?text=Laughter+Chefs%0AS03",
    type: "series",
    language: "hindi",
    dubbed: false,
    genre: ["comedy","reality"],
    quality: "WEB-DL",
    views: "235.72K",
    rating: "8.6",
    status: "ongoing",
    pinned: false,
    featured: false,
    year: 2025,
    description: "Celebrity chefs combine comedy with cooking in this hilarious reality show that delivers endless entertainment.",
    episodes: "S03 Ep 1-36",
    tags: ["WEB-DL","Hindi","Reality"],
    addedDate: "2026-03-17"
  },
  {
    id: "s6",
    title: "Wheel of Fortune (2026) S01 Epi 1-40 Added",
    poster: "https://placehold.co/300x420/16213e/e94560?text=Wheel+of+Fortune%0AS01",
    type: "series",
    language: "hindi",
    dubbed: false,
    genre: ["drama","action"],
    quality: "WEB-DL",
    views: "82.09K",
    rating: "8.0",
    status: "ongoing",
    pinned: false,
    featured: false,
    year: 2026,
    description: "A high-stakes drama where fortunes are made and lost overnight as rival families battle for supremacy in the business world.",
    episodes: "S01 Ep 1-40",
    tags: ["WEB-DL","Hindi"],
    addedDate: "2026-03-16"
  },
  {
    id: "s7",
    title: "Young Sheldon (2017-2024) Season 1-2 Complete",
    poster: "https://placehold.co/300x420/16213e/00d4aa?text=Young+Sheldon%0AS1-S2",
    type: "series",
    language: "english",
    dubbed: false,
    genre: ["comedy","drama"],
    quality: "WEB-DL",
    views: "1.09K",
    rating: "7.7",
    status: "completed",
    pinned: false,
    featured: false,
    year: 2017,
    description: "The hilarious prequel to The Big Bang Theory follows young genius Sheldon Cooper growing up in East Texas.",
    episodes: "S01-S02 Complete",
    tags: ["WEB-DL","English","Comedy"],
    addedDate: "2026-03-15"
  },
  {
    id: "s8",
    title: "Shooting Stars (2022) S01 Complete Hindi-Korean",
    poster: "https://placehold.co/300x420/16213e/8b5cf6?text=Shooting+Stars%0AKorean",
    type: "series",
    language: "dual",
    dubbed: true,
    genre: ["romance","drama"],
    quality: "WEB-DL",
    views: "2.53K",
    rating: "7.6",
    status: "completed",
    pinned: false,
    featured: false,
    year: 2022,
    description: "A Korean romantic drama that takes you behind the scenes of the glittering entertainment industry.",
    episodes: "S01 Complete",
    tags: ["WEB-DL","Dual [Hindi-Korean]","K-Drama"],
    addedDate: "2026-03-14"
  },
  {
    id: "s9",
    title: "Chiraiya (2026) S01 Epi 1-6 Bengali Dubbed",
    poster: "https://placehold.co/300x420/16213e/e94560?text=Chiraiya%0ABengali+Dubbed",
    type: "series",
    language: "dual",
    dubbed: true,
    genre: ["drama","action"],
    quality: "WEB-DL",
    views: "25.06K",
    rating: "8.0",
    status: "ongoing",
    pinned: true,
    featured: false,
    year: 2026,
    description: "An exciting action-drama series about freedom, resilience, and the human spirit in difficult times.",
    episodes: "S01 Ep 1-6",
    tags: ["WEB-DL","Dual [Hindi-Bangla]"],
    addedDate: "2026-03-13"
  },
  {
    id: "s10",
    title: "Siren's Kiss (2026) S01 Ep 1-7 Added",
    poster: "https://placehold.co/300x420/16213e/f5a623?text=Siren's+Kiss%0AS01",
    type: "series",
    language: "dual",
    dubbed: true,
    genre: ["thriller","mystery"],
    quality: "WEB-DL",
    views: "25.12K",
    rating: "7.9",
    status: "ongoing",
    pinned: false,
    featured: false,
    year: 2026,
    description: "A mystery thriller series about a detective who falls into a web of danger while investigating a series of strange disappearances.",
    episodes: "S01 Ep 1-7",
    tags: ["WEB-DL","Multi [Hindi-English]"],
    addedDate: "2026-03-12"
  },
  {
    id: "s11",
    title: "User Not Found (2026) S01 Epi 1-5 Bengali Dubbed",
    poster: "https://placehold.co/300x420/16213e/00d4aa?text=User+Not+Found%0ABengali",
    type: "series",
    language: "bangla",
    dubbed: true,
    genre: ["sci-fi","thriller"],
    quality: "WEB-DL",
    views: "7.3K",
    status: "ongoing",
    rating: "7.4",
    pinned: false,
    featured: false,
    year: 2026,
    description: "A tech thriller that explores the dark side of social media and digital identity in the modern age.",
    episodes: "S01 Ep 1-5",
    tags: ["WEB-DL","Bengali Dubbed ORG"],
    addedDate: "2026-03-11"
  },
  {
    id: "s12",
    title: "Gopal Bhar (2026) S13 Epi 1221-1238 Added",
    poster: "https://placehold.co/300x420/16213e/8b5cf6?text=Gopal+Bhar%0AS13",
    type: "series",
    language: "bangla",
    dubbed: true,
    genre: ["comedy","animation"],
    quality: "WEB-DL",
    views: "91.86K",
    rating: "8.5",
    status: "ongoing",
    pinned: false,
    featured: false,
    year: 2026,
    description: "The beloved and witty Bengali animated comedy series continues its marathon run with brand new episodes.",
    episodes: "S13 Ep 1221-1238",
    tags: ["WEB-DL","Bangla","Animation"],
    addedDate: "2026-03-10"
  }
];

const SAMPLE_ANIME = [
  {
    id: "a1",
    title: "Jujutsu Kaisen (2026) S03 Ep 1-8 Hindi ORG",
    poster: "https://placehold.co/300x420/0d1117/e94560?text=Jujutsu+Kaisen%0AS03",
    type: "anime",
    language: "dual",
    dubbed: true,
    genre: ["action","fantasy","horror"],
    quality: "WEB-DL",
    views: "85.64K",
    rating: "9.5",
    status: "ongoing",
    pinned: true,
    featured: true,
    year: 2026,
    description: "The supernatural action anime reaches its stunning third season where Jujutsu High sorcerers face their most powerful curse yet.",
    episodes: "S03 Ep 1-8",
    tags: ["WEB-DL","Multi [Hindi-Japanese]","Anime"],
    addedDate: "2026-03-21"
  },
  {
    id: "a2",
    title: "The Daily Life of the Immortal King (2026) S05 Ep 1-11 Hindi ORG",
    poster: "https://placehold.co/300x420/0d1117/f5a623?text=Immortal+King%0AS05",
    type: "anime",
    language: "dual",
    dubbed: true,
    genre: ["action","comedy","fantasy"],
    quality: "WEB-DL",
    views: "20.33K",
    rating: "7.1",
    status: "ongoing",
    pinned: false,
    featured: false,
    year: 2026,
    description: "Wang Ling, the overpowered cultivator, returns for another season of trying to live an ordinary high school life while secretly being the most powerful being alive.",
    episodes: "S05 Ep 1-11",
    tags: ["WEB-DL","Dual [Hindi-Chinese]","Chinese Anime"],
    addedDate: "2026-03-20"
  },
  {
    id: "a3",
    title: "Dragon Ball DAIMA (2025) Season 1 Complete Hindi Dubbed",
    poster: "https://placehold.co/300x420/0d1117/00d4aa?text=Dragon+Ball%0ADAIMA",
    type: "anime",
    language: "hindi",
    dubbed: true,
    genre: ["action","adventure","fantasy"],
    quality: "WEB-DL",
    views: "145.50K",
    rating: "8.7",
    status: "completed",
    pinned: true,
    featured: true,
    year: 2025,
    description: "Goku and friends are mysteriously turned into children and must navigate a strange new Demon Realm to restore themselves.",
    episodes: "S01 Complete",
    tags: ["WEB-DL","Hindi Dubbed","Classic Anime"],
    addedDate: "2026-03-15"
  },
  {
    id: "a4",
    title: "Demon Slayer: Infinity Castle Arc (2026)",
    poster: "https://placehold.co/300x420/0d1117/8b5cf6?text=Demon+Slayer%0AInfinity+Castle",
    type: "anime",
    language: "dual",
    dubbed: true,
    genre: ["action","fantasy","drama"],
    quality: "4K WEB-DL",
    views: "328.90K",
    rating: "9.8",
    status: "ongoing",
    pinned: true,
    featured: true,
    year: 2026,
    description: "Tanjiro and the surviving Hashiras face off against Muzan Kibutsuji and the Twelve Kizuki in the legendary Infinity Castle.",
    episodes: "Movie/Arc - Ongoing",
    tags: ["4K WEB-DL","Dual [Hindi-Japanese]","Premium Anime"],
    addedDate: "2026-03-22"
  }
];

// Combine all content and expose globally
window.ALL_CONTENT = [...SAMPLE_MOVIES, ...SAMPLE_SERIES, ...SAMPLE_ANIME];
window.CATEGORIES = [
  { id: "cat1", name: "Action", slug: "action", icon: "fa-fist-raised" },
  { id: "cat2", name: "Comedy", slug: "comedy", icon: "fa-laugh" },
  { id: "cat3", name: "Romance", slug: "romance", icon: "fa-heart" },
  { id: "cat4", name: "Thriller", slug: "thriller", icon: "fa-skull" },
  { id: "cat5", name: "Horror", slug: "horror", icon: "fa-ghost" },
  { id: "cat6", name: "Sci-Fi", slug: "sci-fi", icon: "fa-rocket" },
  { id: "cat7", name: "Drama", slug: "drama", icon: "fa-masks-theater" },
  { id: "cat8", name: "Fantasy", slug: "fantasy", icon: "fa-hat-wizard" },
  { id: "cat9", name: "Animation", slug: "animation", icon: "fa-wand-magic-sparkles" }
];
